# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/salvatore/Scaricati/Linux_Unreal_Engine_5.5.3

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	space_prototype-Android-DebugGame  \
	space_prototype-Android-Development  \
	space_prototype-Android-Shipping  \
	space_prototype-Linux-DebugGame  \
	space_prototype-Linux-Development  \
	space_prototype-Linux-Shipping  \
	space_prototype-LinuxArm64-DebugGame  \
	space_prototype-LinuxArm64-Development  \
	space_prototype-LinuxArm64-Shipping  \
	space_prototype \
	space_prototypeEditor-Linux-DebugGame  \
	space_prototypeEditor-Linux-Development  \
	space_prototypeEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend space_prototypeEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug space_prototypeEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

space_prototype-Android-DebugGame:
	 $(BUILD) space_prototype Android DebugGame  -Project="/mnt/sda1/Progetti/space_prototype/space_prototype.uproject" $(ARGS)

space_prototype-Android-Development:
	 $(BUILD) space_prototype Android Development  -Project="/mnt/sda1/Progetti/space_prototype/space_prototype.uproject" $(ARGS)

space_prototype-Android-Shipping:
	 $(BUILD) space_prototype Android Shipping  -Project="/mnt/sda1/Progetti/space_prototype/space_prototype.uproject" $(ARGS)

space_prototype-Linux-DebugGame:
	 $(BUILD) space_prototype Linux DebugGame  -Project="/mnt/sda1/Progetti/space_prototype/space_prototype.uproject" $(ARGS)

space_prototype-Linux-Development:
	 $(BUILD) space_prototype Linux Development  -Project="/mnt/sda1/Progetti/space_prototype/space_prototype.uproject" $(ARGS)

space_prototype-Linux-Shipping:
	 $(BUILD) space_prototype Linux Shipping  -Project="/mnt/sda1/Progetti/space_prototype/space_prototype.uproject" $(ARGS)

space_prototype-LinuxArm64-DebugGame:
	 $(BUILD) space_prototype LinuxArm64 DebugGame  -Project="/mnt/sda1/Progetti/space_prototype/space_prototype.uproject" $(ARGS)

space_prototype-LinuxArm64-Development:
	 $(BUILD) space_prototype LinuxArm64 Development  -Project="/mnt/sda1/Progetti/space_prototype/space_prototype.uproject" $(ARGS)

space_prototype-LinuxArm64-Shipping:
	 $(BUILD) space_prototype LinuxArm64 Shipping  -Project="/mnt/sda1/Progetti/space_prototype/space_prototype.uproject" $(ARGS)

space_prototype: space_prototype-Linux-Development

space_prototypeEditor-Linux-DebugGame:
	 $(BUILD) space_prototypeEditor Linux DebugGame  -Project="/mnt/sda1/Progetti/space_prototype/space_prototype.uproject" $(ARGS)

space_prototypeEditor-Linux-Development:
	 $(BUILD) space_prototypeEditor Linux Development  -Project="/mnt/sda1/Progetti/space_prototype/space_prototype.uproject" $(ARGS)

space_prototypeEditor: space_prototypeEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/mnt/sda1/Progetti/space_prototype/space_prototype.uproject" -Game 

.PHONY: $(TARGETS)
